version: '3.4'

networks:
    network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.33.0.0/16

services:
    core.dnp.dappnode.eth:
        build: ./build
        image: core.dnp.dappnode.eth:0.1.3
        container_name: DAppNodeCore-core.dnp.dappnode.eth
        volumes:
            - /opt/dappnode/DNCORE/:/opt/app/DNCORE/
            - /var/run/docker.sock:/var/run/docker.sock
        dns: 172.33.1.2