version: "3.5"
networks:
  dncore_network:
    name: dncore_network
    external: true
services:
  core:
    build: ./src
    restart: "no"
    image: core.dnp.dappnode.eth:0.3.6
    container_name: DAppNodeCore-core.dnp.dappnode.eth
    volumes:
      - /etc:/etc
      - /usr/src/dappnode/:/usr/src/dappnode/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      dncore_network:
        aliases:
          - core.dappnode
          - core.core.dappnode
